export const ENV = {
  CLIENT_URL: process.env.CLIENT_URL,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECURE: process.env.CLOUDINARY_SECURE,

  EMAIL_ADDRESS: process.env.EMAIL_ADDRESS,
  EMAIL_HOST: process.env.EMAIL_HOST,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  EMAIL_PORT: process.env.EMAIL_PORT,
  GMAIL_HOST: process.env.GMAIL_HOST,
  SERVICES: process.env.SERVICES,

  JWT_SECRET: process.env.JWT_SECRET,
  SALT: process.env.SALT,
  SECRET: process.env.SECRET,
  MONGODB_URL: process.env.MONGODB_URL,

  NODE_ENV: process.env.NODE_ENV,
  SERVER_URL: process.env.SERVER_URL,
};
